### ISSUE TITLE
绑定自定义域名出错

### ISSUE THREAD

**Issue by phoenixsky** [caitouyun/docs#2]
caitou deploy --production
使用本地配置文件: caitou.yml
开始部署网站 jsbridge dist
绑定域名... jsbridge.phoneixsky.cn
graphql: lookup jsbridge.phoneixsky.cn on 127.0.0.53:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x41 pc=0x1731f9b]

yaml:
```
site: jsbridge
public: dist
rewrites:
  source: '**'
  destination: /index.html
domains:
  china: jsbridge.phoneixsky.cn
```

已在`jsbridge.phoneixsky.cn`域名配置过cname 指向了 `jsbridge.caitouyun.com`
```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;jsbridge.phoenixsky.cn.		IN	CNAME

;; ANSWER SECTION:
jsbridge.phoenixsky.cn.	155	IN	CNAME	jsbridge.caitouyun.com.

;; Query time: 49 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Thu Apr 08 13:06:03 CST 2021
;; MSG SIZE  rcvd: 87
```

**Comment by wangzuo** [comment]
谢谢反馈，dns更新有延迟，我的网络还没有看到这个 `cname` 更新, 可以用 https://toolbox.googleapps.com/apps/dig/ 检测

**Comment by wangzuo** [comment]
另外，rewrites 机制已经更新, 单页面应用配置为

```yaml
rewrites:
  - source: /*
    destination: /index.html
```
更多详细的 rewrites 文档请查看 [Redirects Rewrites](https://github.com/caitouyun/docs/blob/master/docs/redirects-rewrites.md)

**Comment by phoenixsky** [comment]
感谢提醒，rewrites 已更新
```
site: jsbridge
public: dist
rewrites:
  source: '/*'
  destination: /index.html
domains:
  china: jsbridge.phoneixsky.cn
```

目前在 https://toolbox.googleapps.com/apps/dig/ 已查到。还是报错

![image](https://user-images.githubusercontent.com/6359214/113984180-67847500-987d-11eb-9694-0e4c6f069597.png)

```
jsbridge % caitou version                                    
0.2.9
jsbridge % caitou deploy --production                        
使用本地配置文件: caitou.yml
开始部署网站 jsbridge dist
开始部署上传目录... dist
绑定域名... jsbridge.phoneixsky.cn
graphql: lookup jsbridge.phoneixsky.cn on 127.0.0.53:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x41 pc=0x16168bd]

goroutine 1 [running]:
github.com/caitouyun/caitou/cli/cmd.createDomain(0xc000318108, 0x8, 0xc0000245d0, 0x16, 0x1759927, 0x5, 0xc000256090, 0x25)
        /Users/zuowang/go/src/github.com/caitouyun/caitou/cli/cmd/deploy.go:223 +0x1dd
github.com/caitouyun/caitou/cli/cmd.setupDomains(0xc0004db770, 0x24)
        /Users/zuowang/go/src/github.com/caitouyun/caitou/cli/cmd/deploy.go:202 +0xe5
github.com/caitouyun/caitou/cli/cmd.glob..func1(0x1bdd900, 0xc0002da7a0, 0x0, 0x1, 0x0, 0x0)
        /Users/zuowang/go/src/github.com/caitouyun/caitou/cli/cmd/deploy.go:141 +0xbda
github.com/spf13/cobra.(*Command).execute(0x1bdd900, 0xc0002da790, 0x1, 0x1, 0x1bdd900, 0xc0002da790)
        /Users/zuowang/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1bde380, 0xc000000180, 0x200000003, 0xc000000180)
        /Users/zuowang/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/zuowang/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/caitouyun/caitou/cli/cmd.Execute()
        /Users/zuowang/go/src/github.com/caitouyun/caitou/cli/cmd/root.go:22 +0x31
main.main()
        /Users/zuowang/go/src/github.com/caitouyun/caitou/cli/main.go:6 +0x25
```

**Comment by phoenixsky** [comment]
不知道我这边哪里配置不对，或者说是域名有问题。第一次接触前端，不太懂

**Comment by wangzuo** [comment]
@phoenixsky 应该还是域名dns的问题，我们这边还是查不到。另外如果cname更新成功的话，访问 http://jsbridge.phoneixsky.cn/ 会先访问菜头云服务器，再返回404。请问你是在哪个服务商注册域名？

https://dns.google.com/query?name=jsbridge.phoneixsky.cn&rr_type=CNAME&ecs=

![image](https://user-images.githubusercontent.com/1039026/114001957-02d21600-988f-11eb-87ae-d356226eddc6.png)

**Comment by phoenixsky** [comment]
实在抱歉，抱歉。
域名拼错了
phoenixsky √
phoneixsky ×

现在已经可以成功访问了：[jsbridge.phoenixsky.cn](https://jsbridge.phoenixsky.cn)

**Comment by wangzuo** [comment]
@phoenixsky 感谢反馈，我们也会改善报错信息
